name: Sample request
description: Suggest a code sample that would enhance this 
title: Your sample request
labels: [enhancement, samples]
body:
  - type: markdown
    attributes:
      value: |
        Your issue will be triaged by the RNW team according to [this process](https://github.com/microsoft/react-native-windows/wiki/Triage-Process).
  - type: textarea
    validations:
      required: true
    attributes:
      label: Suggestion
  - type: textarea
    validations:
      required: true
    attributes:
      label: Why a Windows/macOS specific sample?
      description: This repo is not intended to cover generic React Native samples. It only includes desktop-specific scenarios that impact Windows and macOS. Please describe why this sample is specific to these desktop platforms. 
  - type: textarea
    attributes:
      label: Sample code
      description: Include a snippet of the sample code you would expect to find, if relevant.
