name: Required Reviewer Check

on:
  pull_request_review:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  check:
    name: Checking required reviews
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: Automattic/action-required-review@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          requirements-file: .github/required-reviewers.yaml
