name: Required Reviewer Check

on:
  pull_request_review:
  pull_request_target:
    types: [ opened, reopened, synchronize ]

jobs:
  check:
    name: Checking required reviews
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Automattic/action-required-review@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          requirements-file: .github/required-reviewers.yaml
