name: RNW Website Publish

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/website-publish.yml'
      - 'docs/**'
      - 'website/**'

jobs:
  publish_website:
    name: Website Publish
    runs-on: ubuntu-latest
    steps:
    - name: git setup
      run: |
        git config --global user.email "53619745+rnbot@users.noreply.github.com"
        git config --global user.name "React-Native-Windows Bot"
        echo "machine github.com login 53619745+rnbot password ${{ secrets.RNBOT_GH_TOKEN }}" > ~/.netrc
    - name: git checkout
      uses: actions/checkout@v2
    - name: yarn install
      run: yarn install --frozen-lockfile
      working-directory: ./website
    - name: yarn run publish-gh-pages
      env:
        GIT_USER: 53619745+rnbot
      run: yarn run publish-gh-pages
      working-directory: ./website
    - name: git cleanup
      run: rm ~/.netrc
