name: RNW Website CI

on:
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/website-ci.yml'
      - 'docs/**'
      - 'website/**'

jobs:
  website_ci:
    name: Website CI
    runs-on: windows-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v2
    - name: run unbroken
      run: npx unbroken -q -l
